 
name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: root
        password: Azkal182AA
        port: 22
        key:  ${{ secrets.SSH_KEYS }}
        script: whoami && pwd 
  
    

    
  
      

        

      
      
